Repository littlehorse-enterprises/littlehorse, pull requests merged in 2024-02, with the labels that each got.

#655 Expose dashboard on 0.0.0.0
  docker/dashboard/Dockerfile
Labels: enhancement

#661 feat(canary): add run wf latency and duplicated task metrics
  canary/src/main/java/io/littlehorse/canary/aggregator/AggregatorBootstrap.java
  canary/src/main/java/io/littlehorse/canary/aggregator/internal/LatencyMetricExporter.java
  canary/src/main/java/io/littlehorse/canary/aggregator/topology/DuplicatedTaskRunTopology.java
  canary/src/main/java/io/littlehorse/canary/aggregator/topology/LatencyTopology.java
  canary/src/main/java/io/littlehorse/canary/aggregator/topology/MetricsTopology.java
  canary/src/main/java/io/littlehorse/canary/config/CanaryConfig.java
  canary/src/main/java/io/littlehorse/canary/kafka/KafkaTopicBootstrap.java
  canary/src/main/java/io/littlehorse/canary/metronome/Metronome.java
  canary/src/main/java/io/littlehorse/canary/metronome/MetronomeBootstrap.java
  canary/src/main/java/io/littlehorse/canary/metronome/MetronomeTask.java
  canary/src/main/java/io/littlehorse/canary/prometheus/PrometheusExporterServer.java
  canary/src/main/java/io/littlehorse/canary/prometheus/PrometheusMetricStoreExporter.java
  canary/src/main/proto/canary.proto
  canary/src/main/resources/META-INF/microprofile-config.properties
  canary/src/test/java/io/littlehorse/canary/aggregator/topology/LatencyTopologyTest.java
  canary/src/test/java/io/littlehorse/canary/aggregator/topology/MetricsTopologyTest.java
Labels: enhancement, feature

#672 Chores: minor changes
  canary/src/main/java/io/littlehorse/canary/aggregator/internal/ProtobufDeserializationExceptionHandler.java
  canary/src/main/java/io/littlehorse/canary/aggregator/serdes/ProtobufSerdes.java
  canary/src/main/java/io/littlehorse/canary/aggregator/topology/DuplicatedTaskRunTopology.java
  canary/src/main/java/io/littlehorse/canary/config/LittleHorseConfig.java
  canary/src/main/java/io/littlehorse/canary/kafka/KafkaTopicBootstrap.java
  canary/src/main/java/io/littlehorse/canary/metronome/MetronomeTask.java
  canary/src/main/proto/canary.proto
  local-dev/README.md
  local-dev/build.sh
  server/src/main/java/io/littlehorse/server/monitoring/metrics/PrometheusMetricExporter.java
Labels: enhancement

#680 Handle dashboard loading when there's no data
  dashboard/apps/web/app/(main)/components/metrics/TaskExecutionMetrics.tsx
  dashboard/apps/web/app/(main)/components/metrics/WorkflowExecutionMetrics.tsx
  dashboard/apps/web/app/(main)/components/search/MetadataSearchTable.tsx
  dashboard/apps/web/app/(main)/sections/MetadataSearch.tsx
  dashboard/packages/eslint-config-custom/next.js
  dashboard/packages/ui/components/Loader.tsx
Labels: bug

#685 feat(metrics): add new metrics classes
  canary/src/main/java/io/littlehorse/canary/prometheus/PrometheusMetricStoreExporter.java
  server/src/main/java/io/littlehorse/server/KafkaStreamsServerImpl.java
  server/src/main/java/io/littlehorse/server/monitoring/HealthService.java
  server/src/main/java/io/littlehorse/server/monitoring/metrics/LHCacheMetrics.java
  server/src/main/java/io/littlehorse/server/monitoring/metrics/PrometheusMetricExporter.java
  server/src/main/java/io/littlehorse/server/monitoring/metrics/ServerFilterRules.java
  server/src/main/java/io/littlehorse/server/monitoring/metrics/TaskQueueManagerMetrics.java
  server/src/main/java/io/littlehorse/server/streams/taskqueue/OneTaskQueue.java
  server/src/main/java/io/littlehorse/server/streams/taskqueue/TaskQueueManager.java
  server/src/main/java/io/littlehorse/server/streams/util/LHCache.java
Labels: enhancement, server

#691 Define canary topics name
  canary/src/main/java/io/littlehorse/canary/aggregator/topology/DuplicatedTaskRunTopology.java
  canary/src/main/java/io/littlehorse/canary/aggregator/topology/LatencyTopology.java
  canary/src/main/java/io/littlehorse/canary/aggregator/topology/MetricsTopology.java
  canary/src/main/java/io/littlehorse/canary/metronome/Metronome.java
  canary/src/main/java/io/littlehorse/canary/metronome/MetronomeTask.java
  canary/src/main/proto/canary.proto
  server/src/main/java/io/littlehorse/server/monitoring/metrics/TaskQueueManagerMetrics.java
Labels: enhancement
